#undef ACCESS_REGION_NONE
#undef ACCESS_REGION_ALL
#undef ACCESS_REGION_SECURITY
#undef ACCESS_REGION_MEDBAY
#undef ACCESS_REGION_RESEARCH
#undef ACCESS_REGION_ENGINEERING
#undef ACCESS_REGION_COMMAND
#undef ACCESS_REGION_GENERAL
#undef ACCESS_REGION_SUPPLY
#undef ACCESS_REGION_NT

#undef ACCESS_TYPE_NONE
#undef ACCESS_TYPE_CENTCOM
#undef ACCESS_TYPE_STATION
#undef ACCESS_TYPE_SYNDICATE
#undef ACCESS_TYPE_ALL
